"""empty message

Revision ID: 869c40cb12e6
Revises: 
Create Date: 2021-05-16 19:48:02.011120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869c40cb12e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod1', sa.Float(), nullable=True),
    sa.Column('mod2', sa.Float(), nullable=True),
    sa.Column('mod3', sa.Float(), nullable=True),
    sa.Column('avg_mark', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
