"""marks table

Revision ID: bdfd499b5cec
Revises: 60cd23939cb5
Create Date: 2021-05-02 15:30:41.899602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfd499b5cec'
down_revision = '60cd23939cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod1', sa.Float(), nullable=True),
    sa.Column('mod2', sa.Float(), nullable=True),
    sa.Column('mod3', sa.Float(), nullable=True),
    sa.Column('avgMark', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
